apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-cert
spec:
  secretName: cluster-cert-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - api.sandbox.{{ domain_name }}
    - k8s.sandbox.{{ domain_name }}
