image: python:3.12

definitions:
  services:
    docker:
      memory: 3072

    postgres:
      image: postgres:16
      environment:
        POSTGRES_DB: {{ project_slug }}
        POSTGRES_USER: {{ project_slug }}
        POSTGRES_PASSWORD: TESTPASSWORD
{% if use_celery %}
    redis:
      image: redis:stable
{% endif %}

  steps:
    - step: &backend-tests
        name: Backend Tests
        caches:
          - pip
        script:
          - export DATABASE_URL=postgres://{{ project_slug }}:TESTPASSWORD@localhost:5432/{{ project_slug }}
{% if use_celery %}
          - export CELERY_BROKER_URL=redis://127.0.0.1:6379/0
{% endif %}
          - CI=true make backend-test

        services:
{% if use_celery %}
          - redis
{% endif %}
          - postgres

    - step: &check-lint-and-formatting
        name: Check lint and formatting
        caches:
          - pip
        script:
          - make check-lint-and-formatting

{% if create_nextjs_frontend %}
    - step: &check-lint-and-test-frontend
        name: Frontend Lint & Typecheck & Test
        image: node:20
        caches:
          - node
        script:
          - make check-lint-and-test-frontend

    - step: &check-test-frontend
        name: Frontend Unit Tests
        image: node:20
        caches:
          - node
        script:
          - CI=true make frontend-test
{% endif %}

pipelines:
  default:
    - parallel:
      - step: *check-lint-and-formatting
{% if create_nextjs_frontend %}
      - step: *check-lint-and-test-frontend
{% endif %}
      - step: *backend-tests
